md<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
head(md)
md$Date<-as.Date(md$Date,"%d/%m/%Y")
g<-subset(md,md$Date=="2007-02-01"|md$Date=="2007-02-02",na.rm=TRUE)
dt<-paste(g$Date,g$Time)
dt<-as.Date(dt)
dt<-strptime(dt,format='%Y-%m-%d %H:%M:%S')
png(filename="plot2.png")
plot(dt,g$Global_active_power,type='l',ylab="Global Active Power (watts)")
dev.off()